"""Init_Next3

Revision ID: 1804a39adfc2
Revises: f76161e495c9
Create Date: 2023-04-06 18:09:01.849341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1804a39adfc2'
down_revision = 'f76161e495c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
