"""Init

Revision ID: 1f880c7b16ed
Revises: 5ce05a816010
Create Date: 2023-04-10 20:01:22.077956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f880c7b16ed'
down_revision = '5ce05a816010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
