"""Init_Next4

Revision ID: 3f0f7c43c5c8
Revises: 1804a39adfc2
Create Date: 2023-04-06 18:14:53.544859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0f7c43c5c8'
down_revision = '1804a39adfc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
