"""Init

Revision ID: b45b1014f756
Revises: c4fd863b40d6
Create Date: 2023-03-31 14:34:43.782576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45b1014f756'
down_revision = 'c4fd863b40d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
