"""Init

Revision ID: c4fd863b40d6
Revises: 2b55ae8877f7
Create Date: 2023-03-31 00:31:53.311581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fd863b40d6'
down_revision = '2b55ae8877f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_id', table_name='contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###
