"""Init_Next2

Revision ID: f76161e495c9
Revises: b3a77a717c7f
Create Date: 2023-04-06 17:59:54.109396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76161e495c9'
down_revision = 'b3a77a717c7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
